name: "01-EKS"
on:
  workflow_dispatch:

jobs:
  Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Run AWS Terraform Workflow
        uses: zeez-devops/Terraform-Script/.github/workflows/aws-terraform.yml@main
        with:
          gh_environment: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


